name: comic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1   #网络图片缓存
  lazy_load_indexed_stack: ^1.1.0
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  awesome_bottom_bar: ^1.2.4
  webview_flutter: ^4.7.0 #webView 包
  loading_animation_widget: ^1.2.1 # loading加载包
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  pinput: ^5.0.0
  app_launcher: ^1.0.1
  url_launcher: ^6.3.1
  bruno:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^3.0.0
icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: FZDaLTJ
      fonts:
        - asset: assets/fonts/fzDaLTJ.ttf
    - family: FZFWQingYinTiJWL
      fonts:
        - asset: assets/fonts/fzFWQingYinTiJWL.ttf
    - family: FZFWZhuZiAYuanJWM
      fonts:
        - asset: assets/fonts/fzFWZhuZiAYuanJWM.ttf
    - family: SourceHanSans
      fonts:
        - asset: assets/fonts/sourceHanSansMedium.ttc
    - family: Rzzyt
      fonts:
        - asset: assets/fonts/rzzyt.ttf
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
